#!/bin/bash

# Script de déploiement automatisé pour LFD ABA Shop
# Ce script guide l'utilisateur à travers le déploiement sur Render + Vercel

set -e

echo "=========================================="
echo "DÉPLOIEMENT AUTOMATISÉ LFD ABA SHOP"
echo "=========================================="
echo ""

# Vérifier que git est installé
if ! command -v git &> /dev/null; then
    echo "❌ Git n'est pas installé. Veuillez l'installer d'abord."
    exit 1
fi

# Vérifier que les modifications sont poussées
echo "📦 Vérification des modifications locales..."
if [ -n "$(git status --porcelain)" ]; then
    echo "⚠️  Il y a des modifications non poussées. Voulez-vous les pousser ? (y/n)"
    read -r response
    if [ "$response" = "y" ]; then
        git add .
        git commit -m "Pré-déploiement automatisé"
        git push origin main
    fi
fi

echo ""
echo "=========================================="
echo "ÉTAPE 1: Vercel (Frontend)"
echo "=========================================="
echo ""
echo "📋 Instructions Vercel:"
echo "1. Allez sur https://vercel.com"
echo "2. Connectez-vous avec GitHub"
echo "3. Cliquez sur 'Add New Project'"
echo "4. Importez le dépôt: Tobou19/lfd-aba-shop"
echo "5. Configurez:"
echo "   - Framework: Vite"
echo "   - Root Directory: frontend"
echo "   - Build Command: npm run build"
echo "   - Output Directory: dist"
echo "6. Ajoutez la variable d'environnement:"
echo "   - VITE_API_BASE: https://votre-backend-url.onrender.com/api/v1"
echo "7. Cliquez sur Deploy"
echo ""
echo "⏳ Attendez que le déploiement se termine..."
echo "⚠️  IMPORTANT: Notez l'URL Vercel fournie (ex: https://lfd-aba-shop.vercel.app)"
echo ""
read -p "Appuyez sur Entrée une fois le frontend déployé et l'URL notée..."

echo ""
echo "=========================================="
echo "ÉTAPE 2: Render (Backend + PostgreSQL)"
echo "=========================================="
echo ""
echo "📋 Instructions Render:"
echo "1. Allez sur https://render.com"
echo "2. Connectez-vous avec GitHub"
echo "3. Cliquez sur 'New' → 'Web Service'"
echo "4. Importez le dépôt: Tobou19/lfd-aba-shop"
echo "5. Configurez:"
echo "   - Name: lfd-aba-shop-backend"
echo "   - Root Directory: backend"
echo "   - Build Command: npm install && npm run build"
echo "   - Start Command: npm run start:prod"
echo "6. Après création, ajoutez PostgreSQL:"
echo "   - Cliquez sur 'New' → 'Database' → 'PostgreSQL'"
echo "   - Connectez-le au Web Service"
echo "7. Configurez les variables d'environnement:"
echo "   - DATABASE_URL: (auto-généré par Render)"
echo "   - JWT_ACCESS_SECRET: (générez sur https://generate-random.org/api-key)"
echo "   - JWT_REFRESH_SECRET: (générez un autre secret)"
echo "   - CORS_ORIGIN: https://votre-frontend-url.vercel.app"
echo "   - NODE_ENV: production"
echo "   - STORAGE_DRIVER: local"
echo "   - STORAGE_LOCAL_ROOT: ./storage"
echo "   - STORAGE_PUBLIC_BASE_URL: /files"
echo "8. Cliquez sur Deploy"
echo ""
echo "⏳ Attendez que le déploiement se termine..."
echo "⚠️  IMPORTANT: Notez l'URL Render fournie (ex: https://lfd-aba-shop-backend.onrender.com)"
echo ""
read -p "Appuyez sur Entrée une fois le backend déployé et l'URL notée..."

echo ""
echo "=========================================="
echo "ÉTAPE 3: Seed de la Base de Données"
echo "=========================================="
echo ""
echo "📋 Instructions pour peupler la base de données:"
echo "1. Sur Render Dashboard, allez dans votre service backend"
echo "2. Cliquez sur 'Shell' (ou utilisez l'interface de console)"
echo "3. Exécutez: cd backend && npx prisma db seed"
echo ""
echo "⚠️  Cela créera votre compte administrateur:"
echo "   - Email: toboudjilayanxavier@gmail.com"
echo "   - Téléphone: 688758020"
echo "   - Mot de passe: X@vier1st"
echo ""
read -p "Appuyez sur Entrée une fois le seed effectué..."

echo ""
echo "=========================================="
echo "ÉTAPE 4: Mise à jour Vercel"
echo "=========================================="
echo ""
echo "📋 Instructions pour connecter frontend et backend:"
echo "1. Retournez sur Vercel"
echo "2. Allez dans Settings → Environment Variables"
echo "3. Mettez à jour VITE_API_BASE:"
echo "   - Remplacez par: https://votre-backend-url.onrender.com/api/v1"
echo "4. Cliquez sur Save"
echo "5. Redéployez le projet Vercel"
echo ""
read -p "Appuyez sur Entrée une fois terminé..."

echo ""
echo "=========================================="
echo "ÉTAPE 5: Test en Production"
echo "=========================================="
echo ""
echo "📋 Instructions de test:"
echo "1. Ouvrez votre navigateur"
echo "2. Allez sur l'URL Vercel (ex: https://lfd-aba-shop.vercel.app)"
echo "3. Connectez-vous avec:"
echo "   - Email: toboudjilayanxavier@gmail.com"
echo "   - Mot de passe: X@vier1st"
echo "4. Vérifiez que:"
echo "   - La connexion fonctionne"
echo "   - Le tableau de bord s'affiche"
echo "   - Les centres sont visibles"
echo ""
read -p "Appuyez sur Entrée une fois testé..."

echo ""
echo "=========================================="
echo "✅ DÉPLOIEMENT TERMINÉ !"
echo "=========================================="
echo ""
echo "🎉 Votre application LFD ABA SHOP est maintenant en production !"
echo ""
echo "📌 URLs de production:"
echo "   - Frontend: https://votre-frontend-url.vercel.app"
echo "   - Backend: https://votre-backend-url.onrender.com"
echo ""
echo "🔐 Identifiants administrateur:"
echo "   - Email: toboudjilayanxavier@gmail.com"
echo "   - Mot de passe: X@vier1st"
echo ""
echo "📚 Guides disponibles:"
echo "   - GUIDE_DEPLOIEMENT_PRODUCTION.md"
echo "   - GUIDE_UTILISATION_COMPLET.md"
echo "   - GUIDE_DEMARRAGE_RAPIDE.md"
echo ""
